### PR TITLE
cursor is pointer for selectable colors in pallete

### PR DESCRIPTION
**Pull request by Kully**
I think a pointing cursor will provide a better user experience for people who haven't used before. I personally spent a few minutes trying to figure out how to change the active color.

@eonarheim WDYT?

### CODE REVIEW

**Comment by Kully** [comment]
not a great GIF but shows the point

selectable

**Comment by eonarheim** [comment]
I agree 👍 I'll take a look at your pr today

**Comment by Kully** [comment]
> I agree 👍 I'll take a look at your pr today

awesome.

Also, I noticed that you spelled "palette" as "pallete" in a few places in the codebase. Was there a particular reason for that?

**Comment by eonarheim** [comment]
@Kully nope, I'm just a terrible speller over here 😃 feel free to fix the misspellings

**Review by eonarheim — APPROVED** [review]

**Comment by Kully** [comment]
@eonarheim okay fixed the typos

**Comment by eonarheim** [comment]
Thanks for the fix @Kully!

**Pull request merged**
